---
version: "3.7"

## DSL Config
x-influxlog: &syslog
  logging:
    driver: syslog
    options:
      #syslog-address: "udp://{{.Node.Hostname}}:6154"
      #syslog-address: "udp://{{.Swarm.NodeAddr}}:6154"
      syslog-address: "udp://127.0.0.1:6154"
      syslog-format: rfc5424micro
      tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

x-replicas: &replicated
  replicas: 1

x-global: &global
  mode: global

x-worker: &worker
  placement:
    constraints: [node.role == worker]

x-manager: &manager
  placement:
    constraints: [node.role == manager]

x-restart: &on-failure
  restart_policy:
    condition: on-failure
    max_attempts: 3
    delay: 5s

  rollback_config:
    parallelism: 2
    delay: 10s
    monitor: 10s
    order: start-first
    failure_action: continue

  update_config:
    parallelism: 2
    delay: 10s
    monitor: 10s
    order: start-first
    failure_action: rollback

x-stop-grace: &stopperiod
  stop_grace_period: 30s

x-default-healthcheck: &heathcheck-pass
  test: ["CMD", "exit 0"]
  interval: 25s
  timeout: 5s
  retries: 3

x-traefik-off: &traefik-off
  traefik.enabled: "false"

x-traefik-on: &traefik-on
  traefik.enabled: "true"
  traefik.frontend.errors.network.backend: "error"                                                                                                                                                                     
  traefik.frontend.errors.network.query: "/"                                                                                                                                                                             
  traefik.frontend.errors.network.status: "404,500-511"
  traefik.frontned.entrypoints: 'http,https,ws,wss'
  traefik.frontend.priority: "5"
  traefik.port: "80"

x-default-route: &default-route
  <<: *traefik-on
  traefik.frontend.rule: "HostRegexp:{catchall:.*}"
  traefik.frontend.priority: "1"
#<<: *traefik-default-frontend

x-vhost-route: &vhost-route
  <<: *traefik-on
  traefik.frontend.priority: "10"


x-orbiter-disable: &orbiter-off
  orbiter: "false"
  <<: *traefik-off

x-orbiter-enable: &orbiter-on
  orbiter: "true"
  orbiter.up: "3"
  orbiter.down: "1"
  <<: *traefik-on

volumes:

  pg-data:
  odoo-web-data:
  odoo-config:
  odoo-addons:

networks:

  internal:
    external: true
    name: internal

  default:
    external: true
    name: ${DEFAULT_NETWORK}


services:

  db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/
    networks:
      - internal

  odoo11:
    image: odoo:11.0
    deploy:
      <<: *replicated
      <<: *on-failure
      labels:
        <<: *vhost-route
        <<: *orbiter-on
        traefik.port: "8069"
        traefik.frontend.rule: "Host:crm.${DOMAINNAME}"
    depends_on:
      - db
    ports:
      - 8069/tcp
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-config:/etc/odoo
      - odoo-addons:/mnt/extra-addons
    networks:
      - internal
      - default

...
# vim: set sts=2 sw=2 ts=2 et ai:
